jnasc/urls.py
from django.contrib import admin
from django.conf.urls import url,include
from django.urls import path, re_path
from django.views.static import serve
from django.conf import settings


urlpatterns = [
    path('JNASC-admin/', admin.site.urls),
    path('',include('web.urls',namespace='web')),

    re_path('media/(?P<path>.*)$', serve, { 'document_root': settings.MEDIA_ROOT}),
    re_path('static/(?P<path>.*)$', serve, { 'document_root': settings.STATIC_FILE_ROOT}),

]

web/urls.py
from django.conf.urls import url
from . import views
from django.urls import path

app_name = 'web'
urlpatterns = [
    path('',views.index, name="index"),
    path('aboutus/',views.aboutus, name="aboutus"),
    path('events/',views.events, name="events"),
    path('staffs/',views.staffs, name="staffs"),
    path('gallery/',views.gallery, name="gallery"),
    path('Acconts/',views.Acconts, name="Acconts"),
    path('attendance/',views.attendance, name="attendance"),

]

web/models.py
from django.db import models
from django.utils.translation import ugettext_lazy as _
from versatileimagefield.fields import VersatileImageField

role_choices = [
    ('management', 'Management'),
    ('administrative', 'Administrative'),
    ('teacher', 'Teaching Staff'),
    ('students', 'Students')
]
programs_choices = [
    ('arts','Arts'),
    ('games','Games'),
    ('otheractivities','Otheractivities')
]
class ManagementStaff(models.Model):
    name = models.CharField(max_length=128)
    position = models.CharField(max_length=128)
    image = models.ImageField(upload_to="web/management/")
    role = models.CharField(max_length=28, choices=role_choices, default='TeachingStaff')

    class Meta:
        db_table = 'web_management'
        verbose_name = "management"
        verbose_name_plural = "management"

    def __str__(self):
        return self.name


class Gallery(models.Model):
    image = VersatileImageField('Image',upload_to='web/gallery/')

    class Meta:
        db_table = 'web_gallery'
        verbose_name = "gallery"
        verbose_name_plural = "gallery"

    def __str__(self):
        return self.image.url


class Achievements(models.Model):
    name = models.CharField(max_length=128)
    description = models.TextField()
    image = models.ImageField(upload_to="web/achievements/")
    class Meta:
        db_table = 'web_achievements'
        verbose_name = "achievements"
        verbose_name_plural = "achievements"

    def __str__(self):
        return self.name


class Events(models.Model):
    name = models.CharField(max_length=128)
    date = models.DateTimeField(blank=False)
    description = models.TextField()
    image = models.ImageField(upload_to="web/events/")
    programs = models.CharField(max_length=28,choices=programs_choices,default='otheractivities')
    class Meta:
        db_table = 'web_events'
        verbose_name = "events"
        verbose_name_plural = "events"

    def __str__(self):
        return self.name

web/views.py
from django.shortcuts import render
from django.http.response import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from web.models import ManagementStaff,Gallery,Achievements,Events


def index(request):
    management_datas = ManagementStaff.objects.all()
    gallery_datas = Gallery.objects.all()
    achievements_datas = Achievements.objects.all()
    events_datas = Events.objects.all()
    context = {
        "title": "JNASC",
        "caption": "Jamia ",
        "management_datas" : management_datas,
        "gallery_datas" : gallery_datas,
        "achievements_datas" : achievements_datas,
        "events_datas" : events_datas,
        "is_home": True
     }
    return render(request,'web/index.html',context)


def aboutus(request):
    context = {
        "title": "About",
        "caption": "JNASC ",
        "is_aboutus": True
     }

    return render(request,'web/about-us.html',context)


def events(request):
    events_datas = Events.objects.all()
    context = {
        "title": "Events",
        "caption": "JNASC ",
        "events_datas" : events_datas,
        "is_events": True
     }
    return render(request,'web/events.html',context)


def staffs(request):
    management_datas = ManagementStaff.objects.all()
    context = {
        "title": "Staffs",
        "caption": "JNASC ",
        "management_datas" : management_datas,
        "is_staffs": True
     }
    return render(request,'web/staffs.html',context)

def gallery(request):
    gallery_datas = Gallery.objects.all()
    context = {
        "title": "Gallery",
        "caption": "JNASC ",
        "gallery_datas" : gallery_datas,
        "is_gallery": True
     }

    return render(request,'web/gallery.html',context)

def Acconts(request):
    context = {
        "title": "Acconts",
        "caption": "JNASC ",
        "is_aboutus": True
     }

    return render(request,'web/Acconts.html',context)
    
def attendance(request):
    context = {
        "title": "attendance",
        "caption": "JNASC ",
        "is_aboutus": True
     }

    return render(request,'web/attendance.html',context)

templates/web/attendance.html
{% extends 'web/base.html' %}
{% load static %}
{% block content %}

	<section id="spotlight">
		<section class="overlay">
			<h2 class="events-programes" >ATTENDANCE REPORT </h2>
			<a href="#"><span class="icon-globe"></span>jnasc.jamia nadwiyya.org</a>
		</section>
	</section>
	<section id="courses">
		<section class="wrapper">
			<div class="top">
				<h2>ATTENDANCE REPORT</h2>
			</div>
			<div id="tabs" class="tabs">
				<!-- <ul class="tabs-head">
					<li class="ui-state-active"><a href="#tabs-1">UG</a></li>
					<li><a href="#tabs-2">PG</a></li>
				</ul> -->
				<div id="tabs-1" class="tabcontent" >
					<div style="width: 32%;padding: 2%;margin: 0 2% 2% 0;box-shadow: 0 4px 4px 0 rgba(0, 0, 0, 0.1), 0 0 10px rgba(0, 0, 0, 0.1);  background-color: #fff;">
						<h2 style="margin-bottom: 2.5%;font-family: 'quicksand_mediumregular';color: #207cf1;font-size: 1.3em;">Daily Attendance Report </h2>
						<a class="button" href="{% static 'Daily Attendance Report 9-13-converted.pdf' %}"><button type="button" style="background-color: #e7e7e7; border: none;color: #000; padding: 15px 32px; text-align: center;text-decoration: none;display:inline-block;font-size: 16px;margin: 4px 2px;cursor: pointer;">View</button></a>
					</div>
				</div>
				<!-- <div id="tabs-2" class="tabcontent">
					<ul>
						<li>
							<h2>MCom<span>(Computer Application)</span></h2>
							<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sit magni dolores porro deserunt inventore nihil, aliquid ipsa cum praesentium beatae accusamus d.</p>
						</li>
						<li>
							<h2>Msc<span>(Pysics)</span></h2>
							<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Perferendis est sunt, illum omnis suscipit voluptate veritatis id reiciendis. Doloremque similique,.</p>
						</li>
					</ul>
				</div> -->
			</div>
		</section><!--(#courses > wrapper)-->
	</section><!--(#courses)-->

{% endblock %}

templates/web/base.html
<!DOCTYPE html>
<html lang="en">
    <head>
        {% load static %}
        <meta charset="UTF-8">
        <title>{{title}} | {{caption}}</title>

        <meta name="description" content="" />
        <meta name="keywords" content="" />
        <meta name="viewport" content="width=device-width" initial-scale="1.0" />

        <link rel="shortcut icon" type="image/x-icon" href="{% static 'images/fav/fav.ico' %}">

        <link rel="stylesheet" href="{% static 'css/style.css' %}" type="text/css" />
        <link rel="stylesheet" href="{% static 'css/jquery.fancybox.min.css' %}" type="text/css" />
        <link rel="stylesheet" href="{% static 'css/owl.carousel.min.css' %}" type="text/css" />

        <meta property="og:image"content="https://jnasc.jamia.com/static/images/og.png" />
        <meta property="og:url"content="jnasc.jamia nadwiyya.org" />
        <meta property="og:type"content="article" />
        <meta property="og:title"content="JNASC | B.Ed College" />
        <meta property="og:description"content="The B.Ed College shall be a centre of excellence for imparting value based education aimed at promoting inclusive and holistic growth of the leaner with thrust on real time needs." />

        <meta name="twitter:image"content="/static/images/logo.png" />
        <meta property="twitter:url"content="jnasc.jamia nadwiyya.org" />
        <meta property="twitter:type"content="article" />
        <meta name="twitter:title"content="JNASC |  B.Ed College" />
        <meta name="twitter:description"content=" " />

        <script src="{% static 'js/jquery.min.js' %}" type="text/javascript"></script>
        <script src="{% static 'js/script.js' %}" type="text/javascript"></script>
        <script src="{% static 'js/jquery.fancybox.min.js' %}" type="text/javascript"></script>
        <script src="{% static 'js/owl.carousel.min.js' %}" type="text/javascript"></script>
        <script src="{% static 'js/jquery.ui.js' %}" type="text/javascript"></script>
        <!-- <script type="text/javascript">
          $(document).on('click', 'header section.bottom nav ul li',function(){
              $(this).addClass('active').siblings().removeClass('active')
          })
        </script> -->
    </head>
    <body>
        <header>
            <section class="top">
                <section class="wrapper">
                    <ul>
                        <li><a href="mailto:jnascedavanna@gmail.com"><span class="icon icon-mail"></span>jnascedavanna@gmail.com</a></li>
                        <li><a href="#"><span class="icon icon-globe"></span>jnasc.jamia nadwiyya.org</a></li>
                        <li><a href="tel:0483-2704771"><span class="icon icon-phone"></span>0483-2704771</a></li>
                    </ul>
                </section>
            </section><!-- top -->
            <section class="bottom">
                <section class="wrapper">
                    <h1 class="left">
                        <a href="#"><img src="{% static 'images/logo.png' %}" alt=""></a>
                    </h1>
                    <nav class="right">
                        <ul>
                            <li {% if is_home %}class="active"{% endif %}><a href="{% url 'web:index' %}">HOME</a></li>
                            <li {% if is_aboutus %}class="active"{% endif %}><a href="{% url 'web:aboutus' %}">ABOUT</a></li>
                            <li {% if is_events %}class="active"{% endif %}><a href="{% url 'web:events' %}">COURSE & PROGRAMMES</a></li>
                            <li {% if is_staffs %}class="active"{% endif %}><a href="{% url 'web:staffs' %}">STAFFS & STUDENTS</a></li>
                            <li {% if is_gallery %}class="active"{% endif %}><a href="{% url 'web:gallery' %}">GALLERY</a></li>
                            <li ><a href="{% url 'web:Acconts' %}">ACCOUNTS</a>
                            <li ><a href="{% url 'web:attendance' %}">ATTENDANCE REPORT</a>
              								<!-- <div class="drop-down">
              									<ul>
              										<li><img src="{% static 'images/form.png' %}"><a href="">Application form</a></li>
              										<li><img src="{% static 'images/brochure.png' %}"><a href="">Brochure</a></li>
              										<li><img src="{% static 'images/magazine.png' %}"><a href="">E-Magazine</a></li>
              									</ul>
              								</div> -->
			                      </li>
                            <li><a href="#contacts">CONTACT US</a></li>
                        </ul>
                    </nav>
                    <br class="clear"/>
                    <div class="mobile-menu-overlay"></div>
                    <span class="icon-menu-outline"></span>
                    <div class="mobile-menu">
                        <span class="icon-cancel-circled-outline"></span>
                        <ul>
                            <li><a href="{% url 'web:index' %}">HOME</a></li>
                            <li><a href="{% url 'web:aboutus' %}">ABOUT</a></li>
                            <li><a href="{% url 'web:events' %}">COURSE & PROGRAMMES</a></li>
                            <li><a href="{% url 'web:staffs' %}">STAFFS</a></li>
                            <li><a href="{% url 'web:gallery' %}">GALLERY</a></li>
                            <li class="downloads"><a href="#">ACCOUNTS</a>
                            <li ><a href="{% url 'web:attendance' %}">ATTENDANCE REPORT</a>
              								<div class="drop-down">
              									<ul>
              										<li><img src=""><a href="">Application form</a></li>
              										<li><img src=""><a href="">Brochure</a></li>
              										<li><img src=""><a href="">E-Magazine</a></li>
              									</ul>
              								</div>
            						    </li>
                            <li><a href="#contacts">CONTACT US</a></li>
                            <li class="responsive top"><a href="#"><span class="icon icon-mail"></span>jnascedavanna@gmail.com</a></li>
                            <li class="responsive"><a href="#"><span class="icon icon-globe"></span>jnasc.jamia nadwiyya.org</a></li>
                            <li class="responsive"><a href="#"><span class="icon icon-phone"></span>0483-2704771</a></li>
                        </ul>
                    </div>
                </section>
            </section><!-- bottom -->
        </header>

        {% block content %}

        {% endblock %}
        <footer id="contacts">
            <section id="top">
                <section class="wrapper">
                    <div class="top">
                        <h2>Contact Us</h2>
                    </div>
                    <div class="middle">
                        <img class="logo" src="{% static 'images/logo.png' %}" alt="images" />
                        <h1 class="title">Jamia Nadwiyya<br /> B.Ed College</h1>
                        <p>Salah nagar,Edavanna po<br/> Malappuram dist,<br/>pin 676541<br/> Kerala</p>
                    </div>
                    <div class="bottom">
                        <a href="tel:+919696369656"><span class="icon icon-phone"></span>+91 9696369656</a>
                        <a href="mailto:jnascedavanna@gmail.com"><span class="icon icon-mail"></span>jnascedavanna@gmail.com</a>
                        <a href="#"><span class="icon icon-globe"></span>jnasc.jamia nadwiyya.org</a>
                    </div>
                </section> <!--(section.wrapper)-->
            </section> <!--(section.top)-->
            <section id="bottom">
                <section class="wrapper">
                    <ul>
                        <li><p class="left">&copy; 2019 JNASC. All rights reserved.</p></li>
                        <li>
                            <div class="social">
                                <a href="#"><span class="icon icon-twitter"></span></a>
                                <a href="#"><span class="icon icon-facebook"></span></a>
                                <a href="#"><span class="icon icon-instagram"></span></a>
                            </div>
                        </li>
                        <li><p class="right">Developed by <a href="https://techpe.talrop.com/">Techpe</a></p></li>
                    </ul>
                </section><!--(section.wrapper)-->
            </section> <!--(section.bottom)-->
        </footer>
    </body>
</html>

templates/web/gallery.html
{% extends 'web/base.html' %}
{% load static %}
{% block content %}
		<section id="spotlight">
			<section class="overlay">
				<section class="wrapper">
					<h2 class="team">GALLERY</h2>
					<a href="#"><span class="icon-globe"></span>jnasc.jamia nadwiyya.org</a>
				</section><!--#spotlight>#overlay>#wrapper-->
			</section> <!--#spotlight>#overlay-->
		</section> <!--#spotlight-->

		<section id="gallery">
			<section class="wrapper">
				<div class="top">
					<h2>Gallery</h2>
				</div>

					<div class="images">
						<ul>
						 	{% for gallery in gallery_datas %}
							<li><img src="{{gallery.image.crop.400x400}}" alt="image" /></li>
							{% endfor %}
						</ul>
					</div>
			</section>
		</section><!-- gallery -->
{% endblock %}

templates/web/index.html
{% extends 'web/base.html' %}
{% load static %}
{% block content %}
	<section id="spotlight">
		<section class="overlay">
			<section class="wrapper">
				<h1>JAMIA NADWIYYA</h1>
				<h2>B.Ed COLLEGE EDAVANNA</h2>
				<a href="www.ncte.gov.in"><span class="icon-globe"></span>www.ncte.gov.in</a>
			</section><!--#spotlight>#overlay>#wrapper-->
		</section> <!--#spotlight>#overlay-->
	</section> <!--#spotlight-->

	<section id="about">
		<section class="wrapper">
			<div class="top">
				<h2>About Us</h2>
			</div>
			<ul>
				<li>
					<h4>Vision</h4>
					<p>To evolve into a premier teacher education institution, molding eminent teachers with creative minds, innovative ideas and sound practical skill, and shape a future where human values are inculcated for the enrichment of mankind.</p>
				</li>
				<li>
					<h4>Mission</h4>
					<p>
						To impart state of the art knowledge to student teachers undergoing   teacher education and to inculcate in them a high degree of social consciousness  and human values ,there by enabling them  to face  the challenges of life  with courage and conviction  and to train them as a teachers to excel in their profession.
					</p>
				</li>
				<li>
					<h4>History</h4>
					<p>Jamia Nadwiyya Training College owes her genesis and efflorescence to Kerala Nadwathul Mujahideen, the most progressive Muslim religious organization founded in 1950. The college is established and maintained by the central committee of its organization. Jamia Nadwiyya trust board was constituted for the purpose. Dr. Usman Sahib, President of K.N.M was the Chairman of the trust board which established the college. 
					</p>
				</li>
				<li>
					<h4>Objectives</h4>
					<p>TThe institution has the broad objective of being an active agent of change by responding to the needs and challenges of the times .This is achieved basically through the process of education, training and research.
					The primary objective of the institution is to impart post graduate instruction and training in Arabic language and literature  and related disciplines
					</p>
				</li>
			</ul>
			<a href="{% url 'web:aboutus' %}" class="button">VIEW MORE</a>
		</section> <!--(#about>.wrapper)-->
	</section> <!--(#about)-->

	<section id="teams">
		<section class="wrapper">
			<div class="top">
				<h2>Management and Staffs</h2>
			</div>
			{% if management_datas %}
				<ul>
					{% for management in management_datas|slice:":5" %}
					<li>
						<div class="container">
							<div class="image thumb"><img src="{{management.image.url}}" alt=""></div>
							<div class="circle__spin">
								<svg>
									<circle cx="50%" cy="50%" r="96px"></circle>
								</svg>
							</div>
						</div>
						<h4>{{management.name}}</h4>
						<p>{{management.position}}</p>
					</li>
					{% endfor %}
				</ul>
			{% else %}
				<p>No data found</p>
				{% endif %}
			<a href="{% url 'web:staffs' %}" class="button">VIEW MORE</a>
		</section><!--(#teams > wrapper)-->
	</section><!--(#teams)-->

	<section id="courses">
		<section class="wrapper">
			<div class="top">
				<h2>Courses</h2>
			</div>
			<div id="tabs" class="tabs">
				<!-- <ul class="tabs-head">
					<li class="ui-state-active"><a href="#tabs-1">UG</a></li>
					<li><a href="#tabs-2">PG</a></li>
				</ul> -->
				<div id="tabs-1" class="tabcontent">
					<ul>
						<li>
							<h2>Arabic<span></span></h2>
							<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sit magni dolores porro deserunt inventore nihil, aliquid ipsa cum praesentium beatae accusamus d.</p>
						</li>
						<li>
							<h2>English<span></span></h2>
							<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Perferendis est sunt, illum omnis suscipit voluptate veritatis id reiciendis. Doloremque similique,.</p>
						</li>
						<li>
							<h2>Natural Science<span></span></h2>
							<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Id facilis unde quia dicta accusantium distinctio ipsa vitae, optio odio adipisci tenetur, a.</p>
						</li>
						<li>
							<h2>Physical Science<span></span></h2>
							<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Impedit delectus nostrum nemo quo maiores itaque eum corrupti vel quam unde dolore modi r.</p>
						</li>
						<li>
							<h2>Social Science<span></span></h2>
							<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Incidunt possimus ullam officiis eveniet sit porro laboriosam dolor atque, eaque debitis .</p>
						</li>
						<li class="blank">
							<h2><span></span></h2>
							<p></p>
						</li>
					</ul>
				</div>
				<!-- <div id="tabs-2" class="tabcontent">
					<ul>
						<li>
							<h2>MCom<span>(Computer Application)</span></h2>
							<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sit magni dolores porro deserunt inventore nihil, aliquid ipsa cum praesentium beatae accusamus d.</p>
						</li>
						<li>
							<h2>Msc<span>(Pysics)</span></h2>
							<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Perferendis est sunt, illum omnis suscipit voluptate veritatis id reiciendis. Doloremque similique,.</p>
						</li>
					</ul>
				</div> -->
			</div>
		</section><!--(#courses > wrapper)-->
	</section><!--(#courses)-->

	<!-- <section id="videoContainer">
		<video autoplay muted loop id="myVideo">
			<source src="images/video.mp4" type="video/mp4">
		</video>
	</section> -->

	<!-- <section id="departments">
		<section class="wrapper">
			<div class="top">
				<h2>Departments</h2>
			</div>
			<ul>
				<li>
					<h2>Computer science</h2>
					<p>Department of Computer Science started in the year 2012. It offers BCA degree in Computer Science.</p>
				</li>
				<li>
					<h2>Commerce</h2>
					<p>Department of Commerce started in the year 2003.It offers B.Com(Computer Application) and M.Com(Marketing)</p>
				</li>
				<li>
					<h2>Physics</h2>
					<p>The department of physics came into being in 2003 with the starting of BSC Degree programme. In 2013 launched the Post graduate course.</p>
				</li>
				<li>
					<h2>Management Studies</h2>
					<p>We offer BBA (Bachelor of Business Administration) a bachelor's degree in commerce, Arts and business Administration from 2014.</p>
				</li>
				<li>
					<h2>English</h2>
					<p>English had been a part of the Curriculum. Since the inception of the college. But it was only in 2011 that the Undergraduate course in English language and Literature was started.</p>
				</li>
				<li>
					<h2></h2>
					<p></p>
				</li>
			</ul>
		</section><!--(wrapper)-->
	<!-- </section>< -->
	<section id="facilities">
		<section class="wrapper">
			<div class="top">
				<h2>Facilities</h2>
			</div>
			<div class="bottom">
				<div class="right">
					<ul>
						<li>
							<img src="{% static 'images/smart.png' %}">
							<h4>Smart<br>classroom</h4>
						</li>
						<li>
							<img src="{% static 'images/book.png' %}">
							<h4>Library</h4>
						</li>
						<li>
							<img src="{% static 'images/dinner.png' %}">
							<h4>Canteen</h4>
						</li>
						<li>
							<img src="{% static 'images/flask.png' %}">
							<h4>Lab</h4>
						</li>
						<li>
							<img src="{% static 'images/rugby-player-catching-the-ball-on-the-ground.png' %}">
							<h4>Play Ground</h4>
						</li>
					</ul>
				</div>
				<br class="clear" />
			</div>
		</section>
	</section><!-- facilities -->

	<section id="gallery">
		<section class="wrapper">
			<div class="top">
				<h2>Gallery</h2>
			</div>
			<div class="bottom">
				<div class="left">
					<img src="{% static 'images/architecture-building-campus-207729.jpg' %}" alt="" class="featured">
				</div>
				<div class="right">
					<ul>
						{% for gallery in gallery_datas|slice:":6" %}
						<li>
							<a href="{{gallery.image.url}}" data-fancybox="gallery"><img src="{{gallery.image.crop.240x220}}" alt="image" /></a>
						</li>
						{% endfor %}
					</ul>
				</div>
				<br class="clear" />
			</div>
			<a href="{% url 'web:gallery' %}" class="button">See all <span class="icon icon-right"></span></a>
		</section>
	</section><!-- gallery -->

	<section id="achivements">
		<div class="top">
			<h2>Achievements</h2>
		</div>
		<ul class="owl-carousel">
			{% for achievements in achievements_datas %}
			<li class="thumb card">
				<img src="{{achievements.image.url}}" alt="">
				<div class="content">
					<h4>{{achievements.name}}</h4>
					<div class="card">
						<p>{{achievements.description}} </p>
					</div>
				</div>
			</li>
			{% endfor %}
		</ul>
	</section><!--(#achivements)-->

	<section id="events">
		<section class="wrapper">
			<div class="top">
				<h2>Events & Programs</h2>
			</div>
			<div id="eventtabs" class="tabs">
				<ul class="tabs-head">
					<li class="ui-state-active"><a href="#tabs-1">All</a></li>
					<li><a href="#tabs-2">Arts</a></li>
					<li><a href="#tabs-3">Games</a></li>
					<li><a href="#tabs-4">Other activities</a></li>
				</ul>
				<div id="tabs-1" class="tabcontent">
					<ul>
						{% for events in events_datas|slice:":4" %}
							{% if events.programs == 'arts' %}
								<li>
									<div class="top">
										<img src="{{events.image.url}}" alt="image">
									</div>
									<div class="bottom">
										<span class="date">{{events.date.date}}</span>
										<h5>{{events.name}}</h5>
										<p>{{events.description}}</p>
										<a href="" class="button">Read more <span class="icon icon-right"></span></a>
									</div>
								</li>
							{% endif %}
						{% endfor %}

						{% for events in events_datas|slice:":4" %}
							{% if events.programs == 'games' %}
								<li>
									<div class="top">
										<img src="{{events.image.url}}" alt="image">
									</div>
									<div class="bottom">
										<span class="date">{{events.date.date}}</span>
										<h5>{{events.name}}</h5>
										<p>{{events.description}}</p>
										<a href="" class="button">Read more <span class="icon icon-right"></span></a>
									</div>
								</li>
							{% endif %}
						{% endfor %}

						{% for events in events_datas|slice:":4" %}
							{% if events.programs == 'otheractivities' %}
								<li>
									<div class="top">
										<img src="{{events.image.url}}" alt="image">
									</div>
									<div class="bottom">
										<span class="date">{{events.date.date}}</span>
										<h5>{{events.name}}</h5>
										<p>{{events.description}}</p>
										<a href="" class="button">Read more <span class="icon icon-right"></span></a>
									</div>
								</li>
							{% endif %}
						{% endfor %}

					</ul>
				</div>
				<div id="tabs-2" class="tabcontent">
					<ul>
						{% for events in events_datas|slice:":4" %}
							{% if events.programs == 'arts' %}
								<li>
									<div class="top">
										<img src="{{events.image.url}}" alt="image">
									</div>
									<div class="bottom">
										<span class="date">{{events.date.date}}</span>
										<h5>{{events.name}}</h5>
										<p>{{events.description}}</p>
										<a href="" class="button">Read more <span class="icon icon-right"></span></a>
									</div>
								</li>
							{% endif %}
						{% endfor %}
					</ul>
				</div>
				<div id="tabs-3" class="tabcontent">
					<ul>
						{% for events in events_datas %}
							{% if events.programs == 'games' %}
								<li>
									<div class="top">
										<img src="{{events.image.url}}" alt="image">
									</div>
									<div class="bottom">
										<span class="date">{{events.date.date}}</span>
										<h5>{{events.name}}</h5>
										<p>{{events.description}}</p>
										<a href="" class="button">Read more <span class="icon icon-right"></span></a>
									</div>
								</li>
							{% endif %}
						{% endfor %}
					</ul>
				</div>
				<div id="tabs-4" class="tabcontent">
					<ul>
						{% for events in events_datas %}
							{% if events.programs == 'otheractivities' %}
								<li>
									<div class="top">
										<img src="{{events.image.url}}" alt="image">
									</div>
									<div class="bottom">
										<span class="date">{{events.date.date}}</span>
										<h5>{{events.name}}</h5>
										<p>{{events.description}}</p>
										<a href="" class="button">Read more <span class="icon icon-right"></span></a>
									</div>
								</li>
							{% endif %}
						{% endfor %}
					</ul>
				</div>
			</div>
		</section><!--(#evets > wrapper)-->
	</section><!--(#evets)-->
{% endblock %}